### ISSUE TITLE
Problem with Node.js 20.10.0

### ISSUE THREAD

**Issue by frequentsailor** [wibberryd/homebridge-rpi-rts#25]
After Upgrading Node.js to 20.10.0 I get the following error messages:

I have a similar problem:

[10/12/2023, 10:09:33] ====================
[10/12/2023, 10:09:33] ERROR LOADING PLUGIN homebridge-rpi-rts:
[10/12/2023, 10:09:33] TypeError: pigpio.gpioInitialise is not a function
at initializePigpio (/var/lib/homebridge/node_modules/homebridge-rpi-rts/node_modules/pigpio/pigpio.js:54:12)
at new Gpio (/var/lib/homebridge/node_modules/homebridge-rpi-rts/node_modules/pigpio/pigpio.js:158:5)
at Object. (/var/lib/homebridge/node_modules/homebridge-rpi-rts/RpiGpioRts.js:6:16)
at Module._compile (node:internal/modules/cjs/loader:1376:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
at Module.load (node:internal/modules/cjs/loader:1207:32)
at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
at Module.require (node:internal/modules/cjs/loader:1235:19)
at require (node:internal/modules/helpers:176:18)
at Object. (/var/lib/homebridge/node_modules/homebridge-rpi-rts/index.js:1:20)
[10/12/2023, 10:09:33] ====================

Downgrading to Node.js 18.18.0 resolves these errors.

**Comment by meydanb** [comment]
Same here,
any chances for a fix??

**Comment by Nicode70** [comment]
After spending way too much time trying to fix it, I’ve bit the boulet and bought a somfy connectivity kit (https://www.amazon.fr/gp/aw/d/B094YLCZFR?psc=1&ref=ppx_pop_mob_b_asin_title).
It’s not totally integrated with HomeKit but it works with Siri and via shortcuts. It’s not ideal, but it’s enough for me.
